name: Upload resources to Transifex

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update locale files
      run: yarn && yarn copyI18n
    - name: Upload to Transifex
      run: 'curl -i -L --user api:$TRANSIFEX_TOKEN -X PUT -F file=@dist/_locales/en/messages.json https://www.transifex.com/api/2/project/violentmonkey-nex/resource/messagesjson/content/'
      env:
        TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
